# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - readme.adoc
      - docs

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x

    - name: Set up Ruby
      uses: actions/setup-ruby@v1

    # Runs a set of commands using the runners shell
    - name: Install and run wiki.adoc
      run: |
        go get -u -v github.com/chrissexton/wiki.adoc
        go install -v github.com/chrissexton/wiki.adoc
        gem install asciidoctor
        make
        
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "readme-bot@chrissexton.org"
        git config --global user.name "README-bot"
        git diff --quiet || (git add readme.adoc docs && git commit -m "Updated README")
        git push
